import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Anillo Flor de Luna",
    description: "Elegante anillo con diseño floral inspirado en la luz de la luna.",
    price: 1200,
    image: "https://images.pexels.com/photos/3641059/pexels-photo-3641059.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    type: "anillo",
    material: "oro",
  },
  {
    id: "2",
    name: "Collar Pétalos Nocturnos",
    description: "Collar delicado con pétalos que brillan en la oscuridad.",
    price: 1500,
    image: "https://images.pexels.com/photos/11444939/pexels-photo-11444939.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    type: "collar",
    material: "plata",
  },
  {
    id: "3",
    name: "Aretes Jardín Estelar",
    description: "Aretes con diseño de flores que parecen constelaciones.",
    price: 950,
    image: "https://images.pexels.com/photos/3266700/pexels-photo-3266700.jpeg?auto=compress&cs=tinysrgb&w=600",
    type: "aretes",
    material: "oro",
  },
  {
    id: "4",
    name: "Pulsera Enredadera",
    description: "Pulsera que simula una enredadera de flores alrededor de tu muñeca.",
    price: 1100,
    image: "https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=600",
    type: "pulsera",
    material: "plata",
  },
  {
    id: "5",
    name: "Tobillera Rocío Nocturno",
    description: "Tobillera con pequeñas gotas que representan el rocío de la noche.",
    price: 850,
    image: "https://images.pexels.com/photos/3560022/pexels-photo-3560022.jpeg?auto=compress&cs=tinysrgb&w=600",
    type: "tobillera",
    material: "plata",
  },
  {
    id: "6",
    name: "Anillo Espiral Floral",
    description: "Anillo con diseño en espiral adornado con pequeñas flores.",
    price: 1300,
    image: "https://images.pexels.com/photos/1670723/pexels-photo-1670723.jpeg?auto=compress&cs=tinysrgb&w=600",
    type: "anillo",
    material: "oro",
  },
  {
    id: "7",
    name: "Collar Cascada de Estrellas",
    description: "Collar con diseño de flores que caen como una cascada de estrellas.",
    price: 1650,
    image: "https://images.pexels.com/photos/1454168/pexels-photo-1454168.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    type: "collar",
    material: "oro",
  },
  {
    id: "8",
    name: "Aretes Luna Creciente",
    description: "Aretes en forma de luna creciente con detalles florales.",
    price: 980,
    image: "https://images.pexels.com/photos/17528105/pexels-photo-17528105/free-photo-of-luxury-earring-on-lace-ornate-cloth.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    type: "aretes",
    material: "plata",
  },
]

